version: "2"

services:
    openlobby-postgres:
        image: postgres:9.5
        environment:
            - POSTGRES_USER=db
            - POSTGRES_PASSWORD=db
            - POSTGRES_DB=openlobby
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - postgres-data:/var/lib/postgresql/data

    openlobby-es:
        image: openlobby/openlobby-es-czech:latest
        environment:
            - discovery.type=single-node
            - cluster.name=openlobby
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        mem_limit: 1g
        ports:
            - "9200:9200"
        restart: always
        volumes:
            - es-data:/usr/share/elasticsearch/data

    openlobby-server:
        image: openlobby/openlobby-server:latest
        ports:
            - "8010:8010"
        restart: always
        depends_on:
            - openlobby-postgres
            - openlobby-es
        environment:
            - DATABASE_DSN=postgresql://db:db@openlobby-postgres:5432/openlobby
            - ELASTICSEARCH_DSN=http://openlobby-es:9200
            - SECRET_KEY=unsecure-demo-secret-key

    openlobby-app:
        image: openlobby/openlobby-app:latest
        ports:
            - "8020:8020"
        restart: always
        depends_on:
            - openlobby-server
        environment:
            - OPENLOBBY_SERVER_DSN=http://openlobby-server:8010
            - SECRET_KEY=another-demo-secret-key

volumes:
    postgres-data:
        driver: local
    es-data:
        driver: local
